name: Build and Deploy

on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app code
        uses: actions/checkout@v4
        
      - name: Build and push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref_type }}" = "tag" ]; then
            TAG="${{ github.ref_name }}"
          else
            TAG="latest"
          fi
          
          echo "Building image with tag: $TAG"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-app:$TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-app:$TAG

      - name: Update deployment manifest
        if: github.event_name == 'push' && github.ref_type == 'tag'
        uses: actions/checkout@v4
        with:
          repository: vladmgb/kuber_config
          token: ${{ secrets.PAT }}
          
      - name: Update image version
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: |
          sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/docker-app|image: ${{ secrets.DOCKER_USERNAME }}/docker-app:${{ github.ref_name }}|g" application/deployment-app.yaml
          
      - name: Commit changes
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add application/deployment-app.yaml
          git commit -m "Deploy ${{ github.ref_name }}"
          git push
          
      - name: Setup YC CLI and deploy
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: |
         
          curl -s https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          source ~/.bashrc
          
          yc config set token ${{ secrets.YC_TOKEN }}
          
          yc k8s cluster get-credentials ${{ secrets.YC_CLUSTER_ID }} --external
          
          kubectl apply -f application/deployment-app.yaml
