name: Build and Deploy

on:
  push:
    tags: [ '*' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app code
        uses: actions/checkout@v4
        
      - name: Build and push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-app:${{ github.ref_name }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-app:${{ github.ref_name }}
          
      - name: Update deployment manifest
        uses: actions/checkout@v4
        with:
          repository: vladmgb/kuber_config
          token: ${{ secrets.PAT }}
          
      - name: Update image version
        run: |
          # Меняем только image без тега (vladmgb/docker-app -> vladmgb/docker-app:v1.0.0)
          sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/docker-app|image: ${{ secrets.DOCKER_USERNAME }}/docker-app:${{ github.ref_name }}|g" application/deployment-app.yaml
          
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add application/deployment-app.yaml
          git commit -m "Deploy ${{ github.ref_name }}"
          git push
